Fixed: Prevent multiple calls to `ResultReturner.returnData()` in `DialogAPI` button press which throws `IOException` due to connecting to output socket again
```
E/TermuxAPI.ResultReturner: Error in ResultReturner:
java.io.IOException: Connection refused
    at android.net.LocalSocketImpl.connectLocal(Native Method)
    at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:262)
    at android.net.LocalSocket.connect(LocalSocket.java:148)
    at com.termux.api.util.ResultReturner.lambda$returnData$0(ResultReturner.java:158)
```