Fixed: Fix exception for missing `android.nfc.action.TECH_DISCOVERED` meta-data for `NfcAPI$NfcActivity`
https://developer.android.com/guide/topics/connectivity/nfc/nfc#tech-disc

```
W/RegisteredComponentCache: Unable to load component info ResolveInfo{eed0b9c com.termux.api/.apis.NfcAPI$NfcActivity m=0x108000}
org.xmlpull.v1.XmlPullParserException: No android.nfc.action.TECH_DISCOVERED meta-data
    at com.android.nfc.RegisteredComponentCache.parseComponentInfo(RegisteredComponentCache.java:186)
    at com.android.nfc.RegisteredComponentCache.generateComponentsList(RegisteredComponentCache.java:161)
    at com.android.nfc.RegisteredComponentCache$1.onReceive(RegisteredComponentCache.java:66)
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1162)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6247)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```