Fixed(LocationAPI)!: Add `LocationService` to handle `termux-location` commands and use `CountDownLatch` to wait for responses instead of `Thread.sleep()` shenanigans and fix `updates`/`once` commands
The `termux-location -p gps -r updates` will now send responses in an array at root level, where each response will get added as a dict inside the array.

```
[
  {
    "latitude": ...,
    "longitude": ...,
    ...
  },
  {
    "latitude": ...,
    "longitude": ...,
    ...
  }
]
```

Previously, the json response was being attempted to be sent with multiple dicts at root level, which is not valid json, and caused the following exception, apparently since the API was initially added.

Now multiple location responses should be properly received, including being able to run multiple `termux-location` commands at once.

```
java.lang.IllegalStateException: JSON must have only one top-level value.
    at android.util.JsonWriter.beforeValue(JsonWriter.java:522)
    at android.util.JsonWriter.open(JsonWriter.java:240)
    at android.util.JsonWriter.beginObject(JsonWriter.java:223)
    at com.termux.api.apis.LocationAPI.locationToJson(LocationAPI.java:208)
    at com.termux.api.apis.LocationAPI$LocationService$1$2.onLocationChanged(LocationAPI.java:153)
    at android.location.LocationListener.onLocationChanged(LocationListener.java:63)
    at android.location.LocationManager$LocationListenerTransport$1.operate(LocationManager.java:3291)
    at android.location.LocationManager$LocationListenerTransport$1.operate(LocationManager.java:3288)
    at com.android.internal.listeners.ListenerExecutor.lambda$executeSafely$0(ListenerExecutor.java:127)
    at com.android.internal.listeners.ListenerExecutor$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:959)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at com.termux.api.apis.LocationAPI$LocationService$1.writeJson(LocationAPI.java:180)
    at com.termux.api.util.ResultReturner$ResultJsonWriter.writeResult(ResultReturner.java:218)
    at com.termux.api.util.ResultReturner.lambda$returnData$0(ResultReturner.java:342)
    at com.termux.api.util.ResultReturner$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)
    Suppressed: java.lang.Exception: Called by:
        at com.termux.api.util.ResultReturner.returnData(ResultReturner.java:310)
        at com.termux.api.apis.LocationAPI$LocationService.onStartCommand(LocationAPI.java:69)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5147)
        at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2469)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loopOnce(Looper.java:232)
        at android.os.Looper.loop(Looper.java:317)
        at android.app.ActivityThread.main(ActivityThread.java:8705)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```

The `termux-location -r updates` command sends responses for the next 30 seconds, with a minimum interval of 5 seconds. Previously, minimum distance between location updates was 50 meters, but now it is 1 meter to support location updates while walking for people who like to touch grass. In future these parameters can be configurable.

The `updates` command after calling `LocationManager.requestLocationUpdates()` was also not unregistering callbacks before exiting, which resulted in the `Handler (android.os.Handler) {35fcbf7} sending message to a Handler on a dead thread` exception. Now it is called for both `LocationManager.requestLocationUpdates()` and `LocationManager.requestSingleUpdate()` after.

For Android `>= 11`, if Termux:API gets frozen, the Termux:API app will not be able to send back location and other API command responses, and native termux-api commands will hang, sometimes in between responses, like after only getting 1 or 2 location updates before the 30s complete. It is recommended to use `adb shell "settings put global cached_apps_freezer disabled"` to disable freezing, and then at least start Termux:API app once from the launcher in case it was already frozen. Check https://github.com/termux/termux-api/issues/638#issuecomment-1813233924 for more info. You may instead try `termux-api-start` command to start a foreground service, but it may get killed anytime too.