Fixed(NfcAPI): Fix `termux-nfc -t x` resulting in error notification being shown as method was not returned from after sending error resulting in `ResultReturner.returnData()` being called twice
```
Error in ResultReturner:
java.io.IOException: Connection refused
	at android.net.LocalSocketImpl.connectLocal(Native Method)
	at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:259)
	at android.net.LocalSocket.connect(LocalSocket.java:162)
	at com.termux.api.util.ResultReturner.lambda$returnData$0(SourceFile:250)
	at com.termux.api.util.ResultReturner.$r8$lambda$RFR2zSHu5FsJH7JvuCx4CPnUmMY(SourceFile:0)
	at com.termux.api.util.ResultReturner$$ExternalSyntheticLambda0.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1119)
	Suppressed: java.lang.Exception: Called by:
		at com.termux.api.util.ResultReturner.returnData(SourceFile:239)
		at com.termux.api.apis.NfcAPI$NfcActivity.errorNfc(SourceFile:48)
		at com.termux.api.apis.NfcAPI$NfcActivity.onCreate(SourceFile:87)
		at android.app.Activity.performCreate(Activity.java:9155)
		at android.app.Activity.performCreate(Activity.java:9133)
		at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1521)
		at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4262)
		at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4467)
		at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:222)
		at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:133)
		at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:103)
		at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2823)
		at android.os.Handler.dispatchMessage(Handler.java:110)
		at android.os.Looper.loopOnce(Looper.java:248)
		at android.os.Looper.loop(Looper.java:338)
		at android.app.ActivityThread.main(ActivityThread.java:9067)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)

```