Fixed: Do not show `java.io.IOException: Connection refused` error notification if it was due to API server process being killed before it was able to receive the result
If API server is still alive and connection was still refused, only then show notification.

The client API server process may exit early without waiting for result, and trying to send data back to it will fail, since that is expected, do not show notification for that case.

This is done by the `termux-api` native process to send its `pid`, `uid` and `starttime` (time the process started after system boot) values, and those are used to check, if possible, whether API server is still alive or has been killed, check `ResultReturner.isApiServerAlive()` method. A `pid` and `starttime` combo can uniquely identify a process even if pid gets recycled.

Also adds API server label and intent data to `ResultReturner` and `TermuxApiReceiver` errors.

This requires `termux-api` package `v0.60.0`. Related commit https://github.com/termux/termux-api-package/commit/73a586d3460af7f551ec7229304fb1b32aa05c6c.

```
Error in ResultReturner for BatteryStatus command sent by API server (pid=5468, uid=10212, starttime=134305, socketType=abstract):

Intent { flg=0x10 cmp=com.termux.api/.TermuxApiReceiver (has extras) }
Bundle[
api_server_pid: `5468`
api_server_uid: `10212`
socket_input: `8896417c2764bc14-155c-42b4-a9c8-96290d9f45df0bff1d495152`
api_server_starttime: `134305`
socket_output: `b6c3b15029b5e460-155c-4810-9c88-7f55838bc9c13fc7533357`
api_method: `BatteryStatus`
]

Error:
java.io.IOException: Connection refused
    at android.net.LocalSocketImpl.connectLocal(Native Method)
    at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:259)
    at android.net.LocalSocket.connect(LocalSocket.java:162)
    at com.termux.api.util.ResultReturner.lambda$returnData$0(ResultReturner.java:321)
    at com.termux.api.util.ResultReturner$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)
    Suppressed: java.lang.Exception: Called by:
        at com.termux.api.util.ResultReturner.returnData(ResultReturner.java:310)
        at com.termux.api.apis.BatteryStatusAPI.onReceive(BatteryStatusAPI.java:29)
        at com.termux.api.TermuxApiReceiver.doWork(TermuxApiReceiver.java:99)
        at com.termux.api.TermuxApiReceiver.onReceive(TermuxApiReceiver.java:66)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4772)
        at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2436)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loopOnce(Looper.java:232)
        at android.os.Looper.loop(Looper.java:317)
        at android.app.ActivityThread.main(ActivityThread.java:8705)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```

Closes https://github.com/termux/termux-api/issues/782
Closes https://github.com/termux/termux-api/issues/887#issuecomment-4975349171yyyyy